# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BD-ConectaESCOM
spring.datasource.username=postgres
spring.datasource.password=escom

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Thymeleaf y Spring DevTools
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=true
